### ISSUE TITLE
Reporte de Practica de Hilos

### ISSUE THREAD

**Issue by Yeim1129** [SistemasTecTlaxiaco/practica-de-hilos-Yeim1129#2]
[Practica MultiHilos_J Manuel_Hernandez A.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Yeim1129/files/6519008/Practica.MultiHilos_J.Manuel_Hernandez.A.pdf)

**Comment by Nayee123** [comment]
18/20
Califico Nayeli Anai González López

**Comment by josealfredo79** [comment]
Bien hecho y revisado
